on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: sdk/typescript

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: npm
                  cache-dependency-path: sdk/typescript/package-lock.json

            - run: npm ci
            - run: npm run build
            - run: npm test
            - run: npm run lint
